case os:cmd("git rev-parse HEAD") of
    GitSha ->
        GitShaShort = string:slice(GitSha, 0, 8),

        {application, Name, Config} = lists:keyfind(application, 1, CONFIG),
        Env = proplists:get_value(env, Config, []),
        NewEnv = lists:keystore(git_sha, 1, Env, {git_sha, GitShaShort}),

        NewConfig = lists:keystore(env, 1, Config, {env, NewEnv}),
        lists:keystore(application, 1, CONFIG, {application, Name, NewConfig})
end.
